name: Office Gaz Data Email

on:
  schedule:
    - cron: "0 12 */3 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          pip install pygazpar==1.2.0
          pip install pandas
          pip install sib_api_v3_sdk
          pip install bs4
      - run: python ${{ github.workspace }}/mailer.py -u ${{ secrets.GAZPAR_USERNAME_OFFICE }} -p ${{ secrets.GAZPAR_PASSWORD_OFFICE }} -i ${{ secrets.GAZPAR_PCEIDENTIFIER_OFFICE }} -sb ${{ secrets.SENDINBLUE_API_KEY }} -r ${{ secrets.RECIPIENT_EMAIL_OFFICE }}
